[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/desktop"
  to = "/desktop/index.html"
  status = 200

[[redirects]]
  from = "/desktop/"
  to = "/desktop/index.html"
  status = 200

[[redirects]]
  from = "/depth"
  to = "/depth/index.html"
  status = 200

[[redirects]]
  from = "/depth/"
  to = "/depth/index.html"
  status = 200
